import { EmptyPanel, PageHeader } from "@/components/OperationsUI";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Building2, Pencil, Plus } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const emptyClient = { organizationName: "", contactPerson: "", email: "", phone: "" };

export default function Clients() {
  const utils = trpc.useUtils();
  const { data: clients, isLoading } = trpc.operations.clients.list.useQuery();
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<any>(null); const [form, setForm] = useState(emptyClient);
  const refresh = () => { void utils.operations.clients.list.invalidate(); void utils.operations.projects.list.invalidate(); void utils.operations.dashboard.invalidate(); };
  const create = trpc.operations.clients.create.useMutation({ onSuccess: () => { toast.success("Client added."); refresh(); setOpen(false); }, onError: (error) => toast.error(error.message) });
  const update = trpc.operations.clients.update.useMutation({ onSuccess: () => { toast.success("Client updated."); refresh(); setOpen(false); }, onError: (error) => toast.error(error.message) });
  const launch = (client?: any) => { setEditing(client ?? null); setForm(client ? { organizationName: client.organizationName, contactPerson: client.contactPerson, email: client.email, phone: client.phone } : emptyClient); setOpen(true); };
  const save = (event: React.FormEvent) => { event.preventDefault(); if (editing) update.mutate({ id: editing.id, values: form }); else create.mutate(form); };
  return <div className="space-y-7"><PageHeader eyebrow="Client relationships" title="Partners with a clear place." description="Keep client contacts ready for project planning, delivery conversations, and an accurate view of your portfolio." action={<Button onClick={() => launch()} className="bg-[#C9A84C] text-[#080808] hover:bg-[#E8E0D0]"><Plus className="mr-2 h-4 w-4" />Add client</Button>} />
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{isLoading ? <p className="col-span-full py-12 text-center text-sm text-[#A99E8C]">Loading client relationships…</p> : clients?.length ? clients.map((client) => <article key={client.id} className="panel-surface rounded-xl border border-white/10 p-5"><div className="flex items-start justify-between gap-3"><span className="grid h-10 w-10 place-items-center rounded-lg border border-[#C9A84C]/25 bg-[#C9A84C]/10 text-[#C9A84C]"><Building2 className="h-5 w-5" /></span><Button onClick={() => launch(client)} variant="ghost" size="icon" className="text-[#C9A84C] hover:bg-[#C9A84C]/10"><Pencil className="h-4 w-4" /></Button></div><h2 className="font-display mt-5 text-3xl leading-none text-[#E8E0D0]">{client.organizationName}</h2><div className="mt-5 space-y-2 border-t border-white/8 pt-4 text-sm"><p className="text-[#BFB5A3]"><span className="mr-2 text-xs uppercase tracking-[.12em] text-[#847966]">Contact</span>{client.contactPerson}</p><p className="truncate text-[#A99E8C]">{client.email}</p><p className="text-[#A99E8C]">{client.phone}</p></div></article>) : <div className="col-span-full"><EmptyPanel title="Relationships begin with a record." description="Add your first client to link projects and preserve the key contact information." /></div>}</section>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="border-[#C9A84C]/25 bg-[#15130F] text-[#E8E0D0]"><DialogHeader><DialogTitle className="font-display text-3xl">{editing ? "Update client" : "Add a client"}</DialogTitle><DialogDescription className="text-[#A99E8C]">Keep a clean record of the organisation and its primary point of contact.</DialogDescription></DialogHeader><form onSubmit={save} className="mt-3 grid gap-4"><label className="grid gap-2 text-xs text-[#BFB5A3]">Organisation name<Input value={form.organizationName} onChange={(e) => setForm({ ...form, organizationName: e.target.value })} className="border-white/10 bg-black/30" required /></label><label className="grid gap-2 text-xs text-[#BFB5A3]">Contact person<Input value={form.contactPerson} onChange={(e) => setForm({ ...form, contactPerson: e.target.value })} className="border-white/10 bg-black/30" required /></label><label className="grid gap-2 text-xs text-[#BFB5A3]">Email<Input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="border-white/10 bg-black/30" required /></label><label className="grid gap-2 text-xs text-[#BFB5A3]">Phone<Input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} className="border-white/10 bg-black/30" required /></label><Button type="submit" disabled={create.isPending || update.isPending} className="mt-2 bg-[#C9A84C] text-[#080808] hover:bg-[#E8E0D0]">{editing ? "Save client" : "Add client"}</Button></form></DialogContent></Dialog>
  </div>;
}
