import { EmptyPanel, formatDate, PageHeader, StatusPill } from "@/components/OperationsUI";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { FolderKanban, Pencil, Plus } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const dateInput = (value: Date | string) => new Date(value).toISOString().slice(0, 10);
const emptyProject = { clientId: 0, name: "", description: "", startDate: "", deadline: "", status: "planned" as const };

export default function Projects() {
  const utils = trpc.useUtils(); const { data: projects, isLoading } = trpc.operations.projects.list.useQuery(); const { data: clients } = trpc.operations.clients.list.useQuery();
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<any>(null); const [form, setForm] = useState(emptyProject);
  const refresh = () => { void utils.operations.projects.list.invalidate(); void utils.operations.tasks.list.invalidate(); void utils.operations.dashboard.invalidate(); };
  const create = trpc.operations.projects.create.useMutation({ onSuccess: () => { toast.success("Project created."); refresh(); setOpen(false); }, onError: (error) => toast.error(error.message) });
  const update = trpc.operations.projects.update.useMutation({ onSuccess: () => { toast.success("Project updated."); refresh(); setOpen(false); }, onError: (error) => toast.error(error.message) });
  const status = trpc.operations.projects.updateStatus.useMutation({ onSuccess: refresh, onError: (error) => toast.error(error.message) });
  const launch = (project?: any) => { setEditing(project ?? null); setForm(project ? { clientId: project.clientId, name: project.name, description: project.description, startDate: dateInput(project.startDate), deadline: dateInput(project.deadline), status: project.status } : { ...emptyProject, clientId: clients?.[0]?.id ?? 0 }); setOpen(true); };
  const save = (event: React.FormEvent) => { event.preventDefault(); const values = { ...form, startDate: new Date(form.startDate), deadline: new Date(form.deadline) }; if (editing) update.mutate({ id: editing.id, values }); else create.mutate(values); };
  return <div className="space-y-7"><PageHeader eyebrow="Project portfolio" title="Every commitment, kept in view." description="Shape client work around a clear brief, a defined delivery window, and a status that reflects reality." action={<Button onClick={() => launch()} disabled={!clients?.length} className="bg-[#C9A84C] text-[#080808] hover:bg-[#E8E0D0]"><Plus className="mr-2 h-4 w-4" />Create project</Button>} />
    {!clients?.length && <div className="rounded-lg border border-[#FF4D1C]/25 bg-[#FF4D1C]/10 px-4 py-3 text-sm text-[#FFB19B]">Add a client before creating the first project.</div>}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{isLoading ? <p className="col-span-full py-12 text-center text-sm text-[#A99E8C]">Loading project portfolio…</p> : projects?.length ? projects.map((project) => <article key={project.id} className="panel-surface rounded-xl border border-white/10 p-5"><div className="flex items-start justify-between gap-3"><span className="grid h-10 w-10 place-items-center rounded-lg border border-[#C9A84C]/25 bg-[#C9A84C]/10 text-[#C9A84C]"><FolderKanban className="h-5 w-5" /></span><Button onClick={() => launch(project)} variant="ghost" size="icon" className="text-[#C9A84C] hover:bg-[#C9A84C]/10"><Pencil className="h-4 w-4" /></Button></div><p className="mt-5 text-xs uppercase tracking-[.12em] text-[#C9A84C]">{project.clientName}</p><h2 className="font-display mt-1 text-3xl leading-none text-[#E8E0D0]">{project.name}</h2><p className="mt-3 line-clamp-2 text-sm leading-6 text-[#A99E8C]">{project.description}</p><div className="mt-5 flex items-center justify-between border-t border-white/8 pt-4"><select value={project.status} onChange={(e) => status.mutate({ id: project.id, status: e.target.value as any })} className="bg-transparent text-xs text-[#E8E0D0] outline-none"><option value="planned">Planned</option><option value="in_progress">In progress</option><option value="on_hold">On hold</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><StatusPill value={project.status} /></div><p className="mt-4 text-xs text-[#847966]">Deadline · {formatDate(project.deadline)}</p></article>) : <div className="col-span-full"><EmptyPanel title="The portfolio is clear." description="Create the first client project to connect a brief, a deadline, and delivery work." /></div>}</section>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[92vh] overflow-y-auto border-[#C9A84C]/25 bg-[#15130F] text-[#E8E0D0]"><DialogHeader><DialogTitle className="font-display text-3xl">{editing ? "Update project" : "Create a project"}</DialogTitle><DialogDescription className="text-[#A99E8C]">Anchor the work to a client and an intentional delivery window.</DialogDescription></DialogHeader><form onSubmit={save} className="mt-3 grid gap-4"><label className="grid gap-2 text-xs text-[#BFB5A3]">Client<select value={form.clientId} onChange={(e) => setForm({ ...form, clientId: Number(e.target.value) })} className="h-10 rounded-md border border-white/10 bg-black/30 px-3 text-sm text-[#E8E0D0]">{clients?.map((client) => <option key={client.id} value={client.id}>{client.organizationName}</option>)}</select></label><label className="grid gap-2 text-xs text-[#BFB5A3]">Project name<Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="border-white/10 bg-black/30" required /></label><label className="grid gap-2 text-xs text-[#BFB5A3]">Description<Textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="min-h-24 border-white/10 bg-black/30" required /></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-xs text-[#BFB5A3]">Start date<Input type="date" value={form.startDate} onChange={(e) => setForm({ ...form, startDate: e.target.value })} className="border-white/10 bg-black/30" required /></label><label className="grid gap-2 text-xs text-[#BFB5A3]">Deadline<Input type="date" value={form.deadline} onChange={(e) => setForm({ ...form, deadline: e.target.value })} className="border-white/10 bg-black/30" required /></label></div><label className="grid gap-2 text-xs text-[#BFB5A3]">Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as any })} className="h-10 rounded-md border border-white/10 bg-black/30 px-3 text-sm text-[#E8E0D0]"><option value="planned">Planned</option><option value="in_progress">In progress</option><option value="on_hold">On hold</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><Button type="submit" disabled={create.isPending || update.isPending} className="mt-2 bg-[#C9A84C] text-[#080808] hover:bg-[#E8E0D0]">{editing ? "Save project" : "Create project"}</Button></form></DialogContent></Dialog>
  </div>;
}
