import { EmptyPanel, PageHeader, StatusPill } from "@/components/OperationsUI";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { Mail, Pencil, Plus, RotateCcw, UserRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const emptyMember: { name: string; role: string; email: string; status: "active" | "inactive" } = { name: "", role: "", email: "", status: "active" };

export default function TeamMembers() {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const utils = trpc.useUtils();
  const { data: members, isLoading } = trpc.operations.teamMembers.list.useQuery(undefined, { enabled: isAdmin });
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<any>(null);
  const [form, setForm] = useState(emptyMember);
  const refresh = () => { void utils.operations.teamMembers.list.invalidate(); void utils.operations.dashboard.invalidate(); };
  const create = trpc.operations.teamMembers.create.useMutation({ onSuccess: () => { toast.success("Team member added."); refresh(); setOpen(false); }, onError: (error) => toast.error(error.message) });
  const update = trpc.operations.teamMembers.update.useMutation({ onSuccess: () => { toast.success("Team member updated."); refresh(); setOpen(false); }, onError: (error) => toast.error(error.message) });
  const resend = trpc.operations.teamMembers.resendInvitation.useMutation({ onSuccess: () => { toast.success("Invitation resent."); refresh(); }, onError: (error) => toast.error(error.message) });
  const launch = (member?: any) => { setEditing(member ?? null); setForm(member ? { name: member.name, role: member.role, email: member.email, status: member.status } : emptyMember); setOpen(true); };
  const save = (event: React.FormEvent) => { event.preventDefault(); if (editing) update.mutate({ id: editing.id, values: form }); else create.mutate(form); };
  if (!isAdmin) return <EmptyPanel title="Team management is restricted." description="Only the Royal Edit administrator can manage team access and assignment recipients." />;
  return <div className="space-y-7"><PageHeader eyebrow="People & capacity" title="The team behind the work." description="Maintain a clear, current roster so every assignment reaches the right person at the right time." action={isAdmin ? <Button onClick={() => launch()} className="bg-[#C9A84C] text-[#080808] hover:bg-[#E8E0D0]"><Plus className="mr-2 h-4 w-4" />Add team member</Button> : undefined} />
    <section className="panel-surface overflow-hidden rounded-xl border border-white/10"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b border-white/10 bg-black/20 text-[10px] uppercase tracking-[.14em] text-[#847966]"><tr><th className="px-6 py-4 font-medium">Member</th><th className="px-5 py-4 font-medium">Role</th><th className="px-5 py-4 font-medium">Email</th><th className="px-5 py-4 font-medium">Access</th><th className="px-5 py-4"><span className="sr-only">Actions</span></th></tr></thead><tbody className="divide-y divide-white/8">{isLoading ? <tr><td colSpan={5} className="px-6 py-12 text-center text-[#A99E8C]">Loading team records…</td></tr> : members?.length ? members.map((member) => <tr key={member.id} className="transition-colors hover:bg-white/[.025]"><td className="px-6 py-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full border border-[#C9A84C]/25 bg-[#C9A84C]/10 font-display text-lg text-[#C9A84C]">{member.name.slice(0, 1)}</span><span className="font-medium text-[#E8E0D0]">{member.name}</span></div></td><td className="px-5 py-4 text-[#BFB5A3]">{member.role}</td><td className="px-5 py-4 text-[#A99E8C]">{member.email}</td><td className="px-5 py-4"><div className="flex flex-wrap items-center gap-2"><StatusPill value={member.status} /><span className={`rounded-full border px-2 py-1 text-[10px] uppercase tracking-[.12em] ${member.invitationStatus === "accepted" ? "border-[#C9A84C]/25 bg-[#C9A84C]/10 text-[#C9A84C]" : "border-[#FF4D1C]/25 bg-[#FF4D1C]/10 text-[#FFB19B]"}`}>{member.invitationStatus === "accepted" ? "Access active" : "Invite pending"}</span></div></td><td className="px-5 py-4 text-right"><div className="flex justify-end gap-1">{isAdmin && member.invitationStatus !== "accepted" && <Button variant="ghost" size="icon" onClick={() => resend.mutate({ id: member.id })} disabled={resend.isPending} className="text-[#C9A84C] hover:bg-[#C9A84C]/10" title="Resend invitation"><RotateCcw className="h-4 w-4" /></Button>}{isAdmin && <Button variant="ghost" size="icon" onClick={() => launch(member)} className="text-[#C9A84C] hover:bg-[#C9A84C]/10" title="Edit team member"><Pencil className="h-4 w-4" /></Button>}</div></td></tr>) : <tr><td colSpan={5} className="p-6"><EmptyPanel title="Your studio is waiting." description="Add the people who will own the delivery work across your client projects." /></td></tr>}</tbody></table></div></section>
    {isAdmin && <Dialog open={open} onOpenChange={setOpen}><DialogContent className="border-[#C9A84C]/25 bg-[#15130F] text-[#E8E0D0]"><DialogHeader><DialogTitle className="font-display text-3xl">{editing ? "Refine team record" : "Add a team member"}</DialogTitle><DialogDescription className="text-[#A99E8C]">Record the person and role available for task assignment. New members receive an email with a one-time link to set their password.</DialogDescription></DialogHeader><form onSubmit={save} className="mt-3 grid gap-4"><label className="grid gap-2 text-xs text-[#BFB5A3]">Full name<Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="e.g. Kemi Adewale" className="border-white/10 bg-black/30" required /></label><label className="grid gap-2 text-xs text-[#BFB5A3]">Role<Input value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} placeholder="e.g. Creative Director" className="border-white/10 bg-black/30" required /></label><label className="grid gap-2 text-xs text-[#BFB5A3]">Email<Input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="name@royaledit.com" className="border-white/10 bg-black/30" required /></label><label className="grid gap-2 text-xs text-[#BFB5A3]">Availability<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as "active" | "inactive" })} className="h-10 rounded-md border border-white/10 bg-black/30 px-3 text-sm text-[#E8E0D0]"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><Button type="submit" disabled={create.isPending || update.isPending} className="mt-2 bg-[#C9A84C] text-[#080808] hover:bg-[#E8E0D0]"><Mail className="mr-2 h-4 w-4" />{editing ? "Save changes" : "Send invitation"}</Button></form></DialogContent></Dialog>}
  </div>;
}
